

```{r}
intuit_df <- readRDS(file=fs::path(r_objects, "010_intuit_df.rds"))

freq.gcp <- readRDS(file=fs::path(r_objects, "050_freq.gcp.rds"))
freq.cci <- readRDS(file=fs::path(r_objects, "050_freq.cci.rds"))

gcp_to_cci <- readRDS(file=fs::path(r_objects, "050_gcp_to_cci.rds"))
cci_to_gcp <- readRDS(file=fs::path(r_objects, "050_cci_to_gcp.rds"))
gcp_to_cci_df <- readRDS(file=fs::path(r_objects, "050_gcp_to_cci_df.rds"))
cci_to_gcp_df <- readRDS(file=fs::path(r_objects, "050_cci_to_gcp_df.rds"))


```

```{r}
# plot(x = freq.gcp, lwd = 2, xlab = "Score", ylab = "Count")  
# plot(x = freq.cci, lwd = 2, xlab = "Score", ylab = "Count")  

```

```{r}
#| fig-cap: "Equipercentile equating between CCI and GCP"
#| fig-subcap: "Arrows demostrate how a CCI score of 0.5 is equated to a GCP score of 65"
#| fig-cap-location: top
#| label: fig-equiplot

# intuit_df %>%
#   mutate(gcp_prank = percent_rank(gcp),
#          cci_prank = percent_rank(Duke_CCI)) %>%
#   ggplot() +
#     geom_line(aes(x=Duke_CCI, y = cci_prank), color = "blue") +
#     geom_line(aes(x = g, y = gcp_prank), color = "red") +
#     hrbrthemes::theme_ipsum() +
#     scale_x_continuous("CCI", sec.axis = sec_axis(~ .*10+50, name = "GCP", 
#                                                   breaks = c(20, 30, 40, 50, 60, 70, 80),
#                                                   labels = c(20, 30, 40, 50, 60, 70, 80)
#                        )) +
#     scale_y_continuous("Percentile rank") +
#     geom_segment(aes(x = .5, y = 0, xend = .5, yend = .75), arrow = arrow()) +
#     geom_segment(aes(x = .5, y = .75, xend = 1.5, yend = .75), arrow = arrow()) + 
#     geom_segment(aes(x = 1.5, y = .75, xend = 1.5, yend = 1), arrow = arrow()) 



intuit_df %>%
  mutate(gcp_prank = percent_rank(gcp),
         cci_prank = percent_rank(Duke_CCI),
         id = row_number()) %>%
  select(id, Duke_CCI, g, cci_prank, gcp_prank) %>%
  pivot_longer(cols = 2:5, names_to = "n", values_to = "v") %>%
  mutate(test = case_when(str_detect(n, regex("cci", ignore_case=TRUE)) ~ "CCI",
                          str_detect(n, regex("g", ignore_case=TRUE)) ~ "GCP"),
         prank = case_when(str_detect(n, regex("prank", ignore_case=TRUE)) ~ "Prank",
                           TRUE ~ "Value")
  ) %>%
  select(-n) %>%
  pivot_wider(values_from = v, names_from = prank) %>%
  ggplot(aes(x = Value, y = Prank, color = test)) +
    geom_line() +
    hrbrthemes::theme_ipsum() +
    scale_x_continuous("CCI", sec.axis = sec_axis(~ .*10+50, name = "GCP", 
                                                  breaks = c(20, 30, 40, 50, 60, 70, 80),
                                                  labels = c(20, 30, 40, 50, 60, 70, 80)
                       )) +
    scale_y_continuous("Percentile rank") +
    scale_color_manual("Composite", values=c("blue", "red")) +
    geom_segment(aes(x = .5, y = 0, xend = .5, yend = .75), arrow = arrow(), color="black") +
    geom_segment(aes(x = .5, y = .75, xend = 1.5, yend = .75), arrow = arrow(), color="black") + 
    geom_segment(aes(x = 1.5, y = .75, xend = 1.5, yend = 1), arrow = arrow(), color="black") 

ggplot2::ggsave(here::here("Figures", "Fig2.pdf"), device = cairo_pdf)
``` 

```{r}
#| fig-cap: "Crosswalk between CCI and GCP"
#| label: fig-crosswalk
 
cci_to_gcp_df %>%
  mutate(cci_x = 1,
         gcp_x = 2, 
         gcp_y = (equivalent_gcp-50)/10,
         x = (cci*10)%% 2,
         cci_str = str_pad(cci, side = "right", pad = " ", width = 3),
         gcp_str = round(equivalent_gcp, 1)
         ) %>%
  filter(x==0) %>%
  ggplot() +
    geom_segment(aes(x = cci_x, y = cci, xend = gcp_x, yend = gcp_y)) +
    theme_void() +
    scale_y_continuous("CCI", sec.axis = sec_axis(~ .*10+50, name = "GCP", 
                                                  breaks = c(20, 30, 40, 50, 60, 70, 80),
                                                  labels = c(20, 30, 40, 50, 60, 70, 80)
                       )) +
    scale_x_continuous(limits = c(.5, 2.5)) +
    geom_text(aes(x = cci_x, y = cci, label = cci_str), hjust = 1.2) +
    geom_text(aes(x = gcp_x, y = gcp_y, label = gcp_str), hjust = -.2) +
    geom_text(aes(x=.8, y = 0, label = "CCI")) +
    geom_text(aes(x=2.2, y = 0, label = "GCP"))
ggplot2::ggsave(here::here("Figures", "Fig3.pdf"), device = cairo_pdf)
```

# GCP to CCI

```{r}
print(gcp_to_cci)
```

```{r}
#| fig-cap: "GCP equated to CCI"
#| label: fig-gcp-to-cci

gcp_to_cci_df %>%
  ggplot(aes(x = gcp, y = equivalent_cci)) +
    geom_point() +
    hrbrthemes::theme_ipsum()

```

```{r}
#| tbl-cap: "GCP equated to CCI"
#| label: tbl-gcp-to-cci

gcp_to_cci_df %>%
  select(-se) %>%
  gt::gt() %>%
  gt::fmt_number(equivalent_cci, decimals = 2)

```

# CCI to GCP

```{r}
print(cci_to_gcp)
```

```{r}
#| fig-cap: "CCI equated to GCP"
#| label: fig-cci-to-gcp

cci_to_gcp_df %>%
  ggplot(aes(x = cci, y = equivalent_gcp)) +
    geom_point() +
    hrbrthemes::theme_ipsum()

```

```{r}
#| tbl-cap: "CCI equated to GCP"
#| label: tbl-cci-to-gcp

cci_to_gcp_df %>%
  select(-se) %>%
  gt::gt() %>%
  gt::fmt_number(equivalent_gcp, decimals = 2)

```
